create sequence hibernate_sequence start with 1 increment by 1
create table adresa (identificator integer not null, adresa varchar(255), primary key (identificator))
create table masina (numar_inmatriculare varchar(255) not null, an_fabricatie integer, marca varchar(255), id_persoana bigint not null, primary key (numar_inmatriculare))
create table persoana (identificator bigint generated by default as identity, nume varchar(255), primary key (identificator))
alter table masina add constraint FKfa6yf0b98mld7eduueksloohw foreign key (id_persoana) references persoana
create sequence hibernate_sequence start with 1 increment by 1
create table adresa (identificator integer not null, adresa varchar(255), primary key (identificator))
create table masina (numar_inmatriculare varchar(255) not null, an_fabricatie integer, marca varchar(255), id_persoana bigint not null, primary key (numar_inmatriculare))
create table persoana (identificator bigint generated by default as identity, nume varchar(255), primary key (identificator))
alter table masina add constraint FKfa6yf0b98mld7eduueksloohw foreign key (id_persoana) references persoana
