DROP TABLE IF EXISTS persoana;
create table persoana (
       identificator integer generated by default as identity,
       nume varchar(255),
       primary key (identificator)
    );

DROP TABLE IF EXISTS masina;
create table masina (
      numar_inmatriculare varchar(255) not null,
      marca varchar(255),
      id_persoana integer not null,
      an_fabricatie integer not null,
      primary key (numar_inmatriculare)
    );